name: On push - deploy to gh-branches

on: 
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
      
    - name: Install dependencies
    - run: npm install
    - run: npm run-script build
    
    - name: Deploy to branch 'gh-pages'
      uses: JamesIves/github-pages-deploy-action@4.1.4
      env:
        branch: gh-pages
        folder: build
